Added API documentation and trimmed the README.

diff --git a/scripts/githooks/pre-commit b/scripts/githooks/pre-commit
--- a/scripts/githooks/pre-commit
+++ b/scripts/githooks/pre-commit
@@ -5,10 +5,17 @@
 set -e
 set -o pipefail
 
-SRCDIR="$(git rev-parse --show-toplevel)/src"
+BASEDIR="$(git rev-parse --show-toplevel)"
 
 # Perform static analysis.
-cppcheck "$SRCDIR" --enable=warning,style,performance,portability --language=c++ -q --error-exitcode=1
+cppcheck "$BASEDIR/src" --enable=warning,style,performance,portability --language=c++ -q --error-exitcode=1
 
-# Make sure the documentation can be built without any errors.
-#qdoc -redirect-documentation-to-dev-null "$SRCDIR/doc/qtstereoscopy.qdocconf"
+# Make sure the documentation can be built without any errors. We can't rely on qdoc's exit
+# code because it returns zero even when warnings are issued. Instead, we check whether
+# qdoc's output is an empty string (success) or not (failure).
+QDOC_OUTPUT=$(qdoc -redirect-documentation-to-dev-null "$BASEDIR/doc/qtstereoscopy.qdocconf" 2>&1)
+if [ ! -z "$QDOC_OUTPUT" ]
+then
+	echo "Could not build documentation without any warnings/errors."
+	exit 1
+fi
